name: flowdiagramapp
description: "Flow diagram generator application"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  intl: ^0.18.1  # Firebase dependencies
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  fl_chart: ^0.68.0  # Para gráficos y visualización de métricas

  # Los iconos de la aplicación
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Para agregar activos a tu aplicación, añade una sección de activos, como esta:
  assets:
    - assets/templates/
